# https://taskfile.dev

version: "3"

tasks:
  default: 
    cmds:
      - task -l
    silent: true

  test:
    desc: "Test the findingmodel library"
    cmds:
      - echo "Testing library without callout test..."
      - uv run pytest -rs -m "not callout" {{.CLI_ARGS}}
    silent: true

  test-full:
    desc: "Test the findingmodel library"
    env:
      PYDANTIC_ALLOW_MODEL_REQUESTS: "1"
    cmds:
      - echo "Testing library (including call-outs)..."
      - uv run pytest -rs {{.CLI_ARGS}}
    silent: true

  evals:
    desc: "Run all agent evaluation suites"
    cmds:
      - echo "Running all agent evaluations..."
      - uv run python -m evals.model_editor
      - uv run python -m evals.similar_models
      - uv run python -m evals.ontology_match
      - uv run python -m evals.anatomic_search
      # Future: add other agent evals here
    silent: true

  evals:model_editor:
    desc: "Run model_editor evaluation suite"
    cmds:
      - echo "Running model_editor evaluations..."
      - uv run python -m evals.model_editor
    silent: true

  evals:similar_models:
    desc: "Run similar_models evaluation suite"
    cmds:
      - echo "Running similar_models evaluations..."
      - uv run python -m evals.similar_models
    silent: true

  evals:ontology_match:
    desc: "Run ontology_match evaluation suite"
    cmds:
      - echo "Running ontology_match evaluations..."
      - uv run python -m evals.ontology_match
    silent: true

  evals:anatomic_search:
    desc: "Run anatomic_search evaluation suite"
    cmds:
      - echo "Running anatomic_search evaluations..."
      - uv run python -m evals.anatomic_search
    silent: true

  check:
    desc: "Check the findingmodel library"
    cmds:
      - echo "Checking library..."
      - uv run ruff format
      - uv run ruff check --fix
      - uv run mypy src
    silent: true

  build:
    desc: "Build the findingmodel library"
    cmds:
      - echo "Building library..."
      - uv build {{.CLI_ARGS}}
    silent: true

  quiet:
    desc: "Run checks quietly"
    cmds:
      - uv run ruff format --quiet
      - uv run ruff check --fix --quiet
      - uv run mypy src --no-error-summary --no-pretty
      - uv run pytest -q {{.CLI_ARGS}}
    silent: true
  
  publish:
    desc: "Publish the findingmodel library"
    cmds:
      - echo "Publishing library..."
      - uv publish {{.CLI_ARGS}}
    silent: true

  release:
    desc: "Interactive release process"
    cmds:
      - uv run python scripts/release.py {{.CLI_ARGS}}

  release:check:
    desc: "Validate release readiness"
    cmds:
      - uv run python scripts/release.py --check-only {{.CLI_ARGS}}

  release:dry:
    desc: "Dry run of release process"
    cmds:
      - uv run python scripts/release.py --dry-run {{.CLI_ARGS}}

  release:version:
    desc: "Release specific version (use: task release:version -- --version X.Y.Z)"
    cmds:
      - uv run python scripts/release.py {{.CLI_ARGS}}
  
